env:
  global:
  - GITHUB_REPO: proustibat/statsify
    # generate token at https://github.com/settings/tokens/new
    # generate secure with travis encrypt -r username/repository GH_TOKEN=[the token you created before]

language: node_js
node_js: '8'
cache: npm

# create a user token here: https://sonarcloud.io/account/security
# run `travis encrypt your-token-here`
# paste secure token below
addons:
  sonarcloud:
    organization: proustibat-github
    token:
      secure: "KJ96NZNY92Md/soJtxyuJKJZ3oEbYuvhTyxFkDkjpbjysQE7nFtnpCIp8Q0zdOqLV0mi8eH6NfyP8lzyo6TW/GyyCuSzn1AlDPYlu9a6DZj8QoVsvw/R8jJhm++pndji4mU4dqk1ip3kiCiXozTsFMqmarbVXIbCfRsWbW9j4Hi39yBVsOh7IBPwvXOXAOj5B1DsY/e0PW19jM37KbNQfFPfmoqW1TX6S8V4Zetg54FgHcn7n1xybC4zED6BaCBazrOd5jMWaYckHIp+10Xl4+Ff8ffX7JSQFNEcSKS021h/VuaJF3apI50C+FHKHsQwvUJfhnjFcdelYbV0OH0797cxtZOwyGveYPAt5nInnVrbfPU7UPb1E+6LNCYX7CtfPt9sZbRzJ2ebMxYv8npwCgQSS1h4WbmA44KCOpju54pOEhFFdnsS6oBzVaG6PpOZmENa8osDFyoT+Ag5NTanttnO0qB0oMpS+lDsMKM/V3ZUlcyvgIVHO1NrNcY4nMwKxYVkNu0sCnjV82oPrIpZ83AYdeKJZgbbyiPz9iaUVeJOHpEXjbiP6sAFI0BSx9RevZXqCKkOPFz6i+EM64tDyZAkIVskKn+pejpYV1CoxIeWL1BXkq/NTJeo1ajeiwfRv/2YznKv1oL7/egvvW9WibqLnBVvP/YXJgmjRnjjig8="

before_install:
- npm install -g ionic@3.19.0 cordova@8.0.0

install:
- npm install
- ionic cordova platform add android

script:
- npm run tslint:codeclimate
- npm run lint
- ionic cordova build android
- bash sonar.sh

# Here we want to check out where we are.
# We only want to update Github Pages if we're building
# the master branch of the original repository, so we
# have to check $TRAVIS_PULL_REQUEST and $TRAVIS_BRANCH.
# If we are here, we run bash deploy.sh
after_success:
# - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh
